name: Code quality

on:
  pull_request:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install lib dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false # Better for building libraries

      - name: Test code
        run: yarn test --coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v5

      # - name: Lint code
      #   run: yarn lint

      - name: Typecheck code
        run: yarn typescript
